# Generated by Django 5.2.1 on 2025-05-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'Math'), ('reading', 'Reading'), ('spelling', 'Spelling')], max_length=20)),
                ('prompt', models.TextField()),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
