# Generated by Django 5.2.1 on 2025-06-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_readingpassage_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_text', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_num', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
