# Generated by Django 5.2.1 on 2025-06-06 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_readingpassage_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_genre', models.CharField(max_length=50)),
                ('prompt_reading_level', models.CharField(max_length=20)),
                ('prompt_preferred_length', models.CharField(max_length=20)),
                ('prompt_fiction_pref', models.CharField(max_length=20)),
                ('passage_text', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age_or_grade', models.CharField(help_text="E.g. '8', '3rd grade', etc.", max_length=20)),
                ('reading_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('favorite_subjects', models.CharField(help_text="Comma-separated list of favorite topics, e.g. 'Animals, Space'.", max_length=200)),
                ('challenging_areas', models.CharField(blank=True, help_text='Comma-separated list of areas student finds challenging.', max_length=200)),
                ('learning_styles', models.CharField(help_text='Comma-separated: Visual, Auditory, Kinesthetic, Verbal.', max_length=100)),
                ('preferred_length', models.CharField(choices=[('Short', 'Short (50–100 words)'), ('Medium', 'Medium (100–200 words)'), ('Long', 'Long (200+ words)')], max_length=20)),
                ('interests', models.CharField(blank=True, help_text="Comma-separated hobbies, e.g. 'Soccer, Drawing'.", max_length=200)),
                ('fiction_preference', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction'), ('Both', 'Both / No preference')], max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
