# Generated by Django 5.2.1 on 2025-07-09 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_generatedquestionset_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='age_or_grade',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='challenging_areas',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='favorite_subjects',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='fiction_preference',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='learning_styles',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='preferred_length',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='reading_level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='favorite_subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='notes',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
