# Generated by Django 5.2.1 on 2025-07-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_spellingquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellingquestion',
            name='audio_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='spellingquestion',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
