# Generated by Django 5.2.1 on 2025-07-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_studentprofile_additional_notes_and_more'),
        ('api', '0005_rename_additional_notes_studentprofile_notes_and_more'),
        ('api', '0006_alter_spellingquestion_audio_url_and_more'),
    ]

    operations = [
    ]
