# Generated by Django 5.2.1 on 2025-07-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20250717_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GeneratedQuestionSet',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
