# Generated by Django 5.2.1 on 2025-08-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
