# Generated by Django 5.2.1 on 2025-08-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='math_questions_answered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
